/*
 * Fingoti API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.fingoti.sdk.models;

import com.fingoti.sdk.models.WebhookAttempts;
import com.fingoti.sdk.models.WebhookHeaders;
import com.fingoti.sdk.models.WebhookStatus;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CallLogDto
 */
public class CallLogDtoTest {
    private final CallLogDto model = new CallLogDto();

    /**
     * Model tests for CallLogDto
     */
    @Test
    public void testCallLogDto() {
        // TODO: test CallLogDto
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'webhookId'
     */
    @Test
    public void webhookIdTest() {
        // TODO: test webhookId
    }

    /**
     * Test the property 'webhookNumber'
     */
    @Test
    public void webhookNumberTest() {
        // TODO: test webhookNumber
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'timestamp'
     */
    @Test
    public void timestampTest() {
        // TODO: test timestamp
    }

    /**
     * Test the property 'requestUrl'
     */
    @Test
    public void requestUrlTest() {
        // TODO: test requestUrl
    }

    /**
     * Test the property 'requestHeaders'
     */
    @Test
    public void requestHeadersTest() {
        // TODO: test requestHeaders
    }

    /**
     * Test the property 'requestBody'
     */
    @Test
    public void requestBodyTest() {
        // TODO: test requestBody
    }

    /**
     * Test the property 'count'
     */
    @Test
    public void countTest() {
        // TODO: test count
    }

    /**
     * Test the property 'attempts'
     */
    @Test
    public void attemptsTest() {
        // TODO: test attempts
    }

}
