/*
 * Fingoti API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.fingoti.sdk.models;

import com.fingoti.sdk.models.DevicePeblDto;
import com.fingoti.sdk.models.DeviceVyneDto;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ClaimedDeviceResponse
 */
public class ClaimedDeviceResponseTest {
    private final ClaimedDeviceResponse model = new ClaimedDeviceResponse();

    /**
     * Model tests for ClaimedDeviceResponse
     */
    @Test
    public void testClaimedDeviceResponse() {
        // TODO: test ClaimedDeviceResponse
    }

    /**
     * Test the property 'success'
     */
    @Test
    public void successTest() {
        // TODO: test success
    }

    /**
     * Test the property 'pebl'
     */
    @Test
    public void peblTest() {
        // TODO: test pebl
    }

    /**
     * Test the property 'vyne'
     */
    @Test
    public void vyneTest() {
        // TODO: test vyne
    }

}
