/*
 * Fingoti API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.fingoti.sdk.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for NetworkMac
 */
public class NetworkMacTest {
    private final NetworkMac model = new NetworkMac();

    /**
     * Model tests for NetworkMac
     */
    @Test
    public void testNetworkMac() {
        // TODO: test NetworkMac
    }

    /**
     * Test the property 'ap'
     */
    @Test
    public void apTest() {
        // TODO: test ap
    }

    /**
     * Test the property 'station'
     */
    @Test
    public void stationTest() {
        // TODO: test station
    }

}
