/*
 * Fingoti API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.fingoti.sdk.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for OrganisationPresetsDto
 */
public class OrganisationPresetsDtoTest {
    private final OrganisationPresetsDto model = new OrganisationPresetsDto();

    /**
     * Model tests for OrganisationPresetsDto
     */
    @Test
    public void testOrganisationPresetsDto() {
        // TODO: test OrganisationPresetsDto
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'presetNumber'
     */
    @Test
    public void presetNumberTest() {
        // TODO: test presetNumber
    }

    /**
     * Test the property 'presetName'
     */
    @Test
    public void presetNameTest() {
        // TODO: test presetName
    }

    /**
     * Test the property 'disabled'
     */
    @Test
    public void disabledTest() {
        // TODO: test disabled
    }

    /**
     * Test the property 'ssid'
     */
    @Test
    public void ssidTest() {
        // TODO: test ssid
    }

}
