/*
 * Fingoti API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.fingoti.sdk.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for OrganisationResponse
 */
public class OrganisationResponseTest {
    private final OrganisationResponse model = new OrganisationResponse();

    /**
     * Model tests for OrganisationResponse
     */
    @Test
    public void testOrganisationResponse() {
        // TODO: test OrganisationResponse
    }

    /**
     * Test the property 'success'
     */
    @Test
    public void successTest() {
        // TODO: test success
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'disabled'
     */
    @Test
    public void disabledTest() {
        // TODO: test disabled
    }

    /**
     * Test the property 'organisationNumber'
     */
    @Test
    public void organisationNumberTest() {
        // TODO: test organisationNumber
    }

    /**
     * Test the property 'organisationName'
     */
    @Test
    public void organisationNameTest() {
        // TODO: test organisationName
    }

    /**
     * Test the property 'organisationHandle'
     */
    @Test
    public void organisationHandleTest() {
        // TODO: test organisationHandle
    }

    /**
     * Test the property 'isBusiness'
     */
    @Test
    public void isBusinessTest() {
        // TODO: test isBusiness
    }

    /**
     * Test the property 'isPartner'
     */
    @Test
    public void isPartnerTest() {
        // TODO: test isPartner
    }

    /**
     * Test the property 'partnerId'
     */
    @Test
    public void partnerIdTest() {
        // TODO: test partnerId
    }

    /**
     * Test the property 'mainContact'
     */
    @Test
    public void mainContactTest() {
        // TODO: test mainContact
    }

    /**
     * Test the property 'mainAddress'
     */
    @Test
    public void mainAddressTest() {
        // TODO: test mainAddress
    }

    /**
     * Test the property 'billingContact'
     */
    @Test
    public void billingContactTest() {
        // TODO: test billingContact
    }

    /**
     * Test the property 'billingAddress'
     */
    @Test
    public void billingAddressTest() {
        // TODO: test billingAddress
    }

    /**
     * Test the property 'deliveryContact'
     */
    @Test
    public void deliveryContactTest() {
        // TODO: test deliveryContact
    }

    /**
     * Test the property 'deliveryAddress'
     */
    @Test
    public void deliveryAddressTest() {
        // TODO: test deliveryAddress
    }

    /**
     * Test the property 'vatNumber'
     */
    @Test
    public void vatNumberTest() {
        // TODO: test vatNumber
    }

    /**
     * Test the property 'credit'
     */
    @Test
    public void creditTest() {
        // TODO: test credit
    }

    /**
     * Test the property 'registeredOn'
     */
    @Test
    public void registeredOnTest() {
        // TODO: test registeredOn
    }

    /**
     * Test the property 'adminRole'
     */
    @Test
    public void adminRoleTest() {
        // TODO: test adminRole
    }

    /**
     * Test the property 'readRole'
     */
    @Test
    public void readRoleTest() {
        // TODO: test readRole
    }

}
