/*
 * Fingoti API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.fingoti.sdk.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for OrganisationTenantDto
 */
public class OrganisationTenantDtoTest {
    private final OrganisationTenantDto model = new OrganisationTenantDto();

    /**
     * Model tests for OrganisationTenantDto
     */
    @Test
    public void testOrganisationTenantDto() {
        // TODO: test OrganisationTenantDto
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'organisationNumber'
     */
    @Test
    public void organisationNumberTest() {
        // TODO: test organisationNumber
    }

    /**
     * Test the property 'organisationName'
     */
    @Test
    public void organisationNameTest() {
        // TODO: test organisationName
    }

    /**
     * Test the property 'subscriptionId'
     */
    @Test
    public void subscriptionIdTest() {
        // TODO: test subscriptionId
    }

    /**
     * Test the property 'isBusiness'
     */
    @Test
    public void isBusinessTest() {
        // TODO: test isBusiness
    }

    /**
     * Test the property 'trialUsed'
     */
    @Test
    public void trialUsedTest() {
        // TODO: test trialUsed
    }

    /**
     * Test the property 'disabled'
     */
    @Test
    public void disabledTest() {
        // TODO: test disabled
    }

}
