/*
 * Fingoti API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.fingoti.sdk.models;

import com.fingoti.sdk.models.AzureMessage;
import com.fingoti.sdk.models.GatewayClaim;
import com.fingoti.sdk.models.GatewayGpio;
import com.fingoti.sdk.models.GatewayI2c;
import com.fingoti.sdk.models.GatewayMqtt;
import com.fingoti.sdk.models.GatewayNetwork;
import com.fingoti.sdk.models.GatewaySchedule;
import com.fingoti.sdk.models.GatewayTimer;
import com.fingoti.sdk.models.GatewayUart;
import com.fingoti.sdk.models.GatewayWifi;
import com.fingoti.sdk.models.PeblDevice;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PeblGateway
 */
public class PeblGatewayTest {
    private final PeblGateway model = new PeblGateway();

    /**
     * Model tests for PeblGateway
     */
    @Test
    public void testPeblGateway() {
        // TODO: test PeblGateway
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'partNumber'
     */
    @Test
    public void partNumberTest() {
        // TODO: test partNumber
    }

    /**
     * Test the property 'systemOs'
     */
    @Test
    public void systemOsTest() {
        // TODO: test systemOs
    }

    /**
     * Test the property 'systemVersion'
     */
    @Test
    public void systemVersionTest() {
        // TODO: test systemVersion
    }

    /**
     * Test the property 'lastUpdated'
     */
    @Test
    public void lastUpdatedTest() {
        // TODO: test lastUpdated
    }

    /**
     * Test the property 'lastMessage'
     */
    @Test
    public void lastMessageTest() {
        // TODO: test lastMessage
    }

    /**
     * Test the property 'claim'
     */
    @Test
    public void claimTest() {
        // TODO: test claim
    }

    /**
     * Test the property 'gpio'
     */
    @Test
    public void gpioTest() {
        // TODO: test gpio
    }

    /**
     * Test the property 'timer'
     */
    @Test
    public void timerTest() {
        // TODO: test timer
    }

    /**
     * Test the property 'wifi'
     */
    @Test
    public void wifiTest() {
        // TODO: test wifi
    }

    /**
     * Test the property 'mqtt'
     */
    @Test
    public void mqttTest() {
        // TODO: test mqtt
    }

    /**
     * Test the property 'network'
     */
    @Test
    public void networkTest() {
        // TODO: test network
    }

    /**
     * Test the property 'schedule'
     */
    @Test
    public void scheduleTest() {
        // TODO: test schedule
    }

    /**
     * Test the property 'device'
     */
    @Test
    public void deviceTest() {
        // TODO: test device
    }

    /**
     * Test the property 'uart'
     */
    @Test
    public void uartTest() {
        // TODO: test uart
    }

    /**
     * Test the property 'i2c'
     */
    @Test
    public void i2cTest() {
        // TODO: test i2c
    }

}
