/*
 * Fingoti API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.fingoti.sdk.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for UartSetup
 */
public class UartSetupTest {
    private final UartSetup model = new UartSetup();

    /**
     * Model tests for UartSetup
     */
    @Test
    public void testUartSetup() {
        // TODO: test UartSetup
    }

    /**
     * Test the property 'baudrate'
     */
    @Test
    public void baudrateTest() {
        // TODO: test baudrate
    }

    /**
     * Test the property 'databits'
     */
    @Test
    public void databitsTest() {
        // TODO: test databits
    }

    /**
     * Test the property 'parity'
     */
    @Test
    public void parityTest() {
        // TODO: test parity
    }

    /**
     * Test the property 'stopbits'
     */
    @Test
    public void stopbitsTest() {
        // TODO: test stopbits
    }

}
