/*
 * Fingoti API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.fingoti.sdk.models;

import java.util.Objects;
import java.util.Arrays;
import com.fingoti.sdk.models.AzureMessageContent;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.fingoti.sdk.JSON;

/**
 * AzureMessage
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-01-16T16:45:33.786096900Z[Europe/London]")
public class AzureMessage {
  public static final String SERIALIZED_NAME_PUSH = "push";
  @SerializedName(SERIALIZED_NAME_PUSH)
  private List<AzureMessageContent> push = null;

  public static final String SERIALIZED_NAME_RESPONSE = "response";
  @SerializedName(SERIALIZED_NAME_RESPONSE)
  private List<AzureMessageContent> response = null;

  public static final String SERIALIZED_NAME_OVERFLOW = "overflow";
  @SerializedName(SERIALIZED_NAME_OVERFLOW)
  private List<AzureMessageContent> overflow = null;

  public AzureMessage() {
  }

  public AzureMessage push(List<AzureMessageContent> push) {
    
    this.push = push;
    return this;
  }

  public AzureMessage addPushItem(AzureMessageContent pushItem) {
    if (this.push == null) {
      this.push = new ArrayList<>();
    }
    this.push.add(pushItem);
    return this;
  }

   /**
   * Get push
   * @return push
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<AzureMessageContent> getPush() {
    return push;
  }


  public void setPush(List<AzureMessageContent> push) {
    this.push = push;
  }


  public AzureMessage response(List<AzureMessageContent> response) {
    
    this.response = response;
    return this;
  }

  public AzureMessage addResponseItem(AzureMessageContent responseItem) {
    if (this.response == null) {
      this.response = new ArrayList<>();
    }
    this.response.add(responseItem);
    return this;
  }

   /**
   * Get response
   * @return response
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<AzureMessageContent> getResponse() {
    return response;
  }


  public void setResponse(List<AzureMessageContent> response) {
    this.response = response;
  }


  public AzureMessage overflow(List<AzureMessageContent> overflow) {
    
    this.overflow = overflow;
    return this;
  }

  public AzureMessage addOverflowItem(AzureMessageContent overflowItem) {
    if (this.overflow == null) {
      this.overflow = new ArrayList<>();
    }
    this.overflow.add(overflowItem);
    return this;
  }

   /**
   * Get overflow
   * @return overflow
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<AzureMessageContent> getOverflow() {
    return overflow;
  }


  public void setOverflow(List<AzureMessageContent> overflow) {
    this.overflow = overflow;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AzureMessage azureMessage = (AzureMessage) o;
    return Objects.equals(this.push, azureMessage.push) &&
        Objects.equals(this.response, azureMessage.response) &&
        Objects.equals(this.overflow, azureMessage.overflow);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(push, response, overflow);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AzureMessage {\n");
    sb.append("    push: ").append(toIndentedString(push)).append("\n");
    sb.append("    response: ").append(toIndentedString(response)).append("\n");
    sb.append("    overflow: ").append(toIndentedString(overflow)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("push");
    openapiFields.add("response");
    openapiFields.add("overflow");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to AzureMessage
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!AzureMessage.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in AzureMessage is not found in the empty JSON string", AzureMessage.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!AzureMessage.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `AzureMessage` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      if (jsonObj.get("push") != null && !jsonObj.get("push").isJsonNull()) {
        JsonArray jsonArraypush = jsonObj.getAsJsonArray("push");
        if (jsonArraypush != null) {
          // ensure the json data is an array
          if (!jsonObj.get("push").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `push` to be an array in the JSON string but got `%s`", jsonObj.get("push").toString()));
          }

          // validate the optional field `push` (array)
          for (int i = 0; i < jsonArraypush.size(); i++) {
            AzureMessageContent.validateJsonObject(jsonArraypush.get(i).getAsJsonObject());
          };
        }
      }
      if (jsonObj.get("response") != null && !jsonObj.get("response").isJsonNull()) {
        JsonArray jsonArrayresponse = jsonObj.getAsJsonArray("response");
        if (jsonArrayresponse != null) {
          // ensure the json data is an array
          if (!jsonObj.get("response").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `response` to be an array in the JSON string but got `%s`", jsonObj.get("response").toString()));
          }

          // validate the optional field `response` (array)
          for (int i = 0; i < jsonArrayresponse.size(); i++) {
            AzureMessageContent.validateJsonObject(jsonArrayresponse.get(i).getAsJsonObject());
          };
        }
      }
      if (jsonObj.get("overflow") != null && !jsonObj.get("overflow").isJsonNull()) {
        JsonArray jsonArrayoverflow = jsonObj.getAsJsonArray("overflow");
        if (jsonArrayoverflow != null) {
          // ensure the json data is an array
          if (!jsonObj.get("overflow").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `overflow` to be an array in the JSON string but got `%s`", jsonObj.get("overflow").toString()));
          }

          // validate the optional field `overflow` (array)
          for (int i = 0; i < jsonArrayoverflow.size(); i++) {
            AzureMessageContent.validateJsonObject(jsonArrayoverflow.get(i).getAsJsonObject());
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AzureMessage.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AzureMessage' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AzureMessage> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AzureMessage.class));

       return (TypeAdapter<T>) new TypeAdapter<AzureMessage>() {
           @Override
           public void write(JsonWriter out, AzureMessage value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public AzureMessage read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of AzureMessage given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of AzureMessage
  * @throws IOException if the JSON string is invalid with respect to AzureMessage
  */
  public static AzureMessage fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AzureMessage.class);
  }

 /**
  * Convert an instance of AzureMessage to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

