/*
 * Fingoti API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.fingoti.sdk.models;

import java.util.Objects;
import java.util.Arrays;
import com.fingoti.sdk.models.DeviceBlink;
import com.fingoti.sdk.models.DeviceBus;
import com.fingoti.sdk.models.DeviceCloud;
import com.fingoti.sdk.models.DeviceLocation;
import com.fingoti.sdk.models.DevicePower;
import com.fingoti.sdk.models.DeviceSession;
import com.fingoti.sdk.models.DeviceSupport;
import com.fingoti.sdk.models.DeviceUptime;
import com.fingoti.sdk.models.DeviceVersion;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.fingoti.sdk.JSON;

/**
 * PeblDevice
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-01-16T16:45:33.786096900Z[Europe/London]")
public class PeblDevice {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_KEY = "key";
  @SerializedName(SERIALIZED_NAME_KEY)
  private String key;

  public static final String SERIALIZED_NAME_SUPPORT = "support";
  @SerializedName(SERIALIZED_NAME_SUPPORT)
  private DeviceSupport support;

  public static final String SERIALIZED_NAME_CLOUD = "cloud";
  @SerializedName(SERIALIZED_NAME_CLOUD)
  private DeviceCloud cloud;

  public static final String SERIALIZED_NAME_UPTIME = "uptime";
  @SerializedName(SERIALIZED_NAME_UPTIME)
  private DeviceUptime uptime;

  public static final String SERIALIZED_NAME_ACTIVITY = "activity";
  @SerializedName(SERIALIZED_NAME_ACTIVITY)
  private Boolean activity;

  public static final String SERIALIZED_NAME_COLOUR = "colour";
  @SerializedName(SERIALIZED_NAME_COLOUR)
  private List<Integer> colour = null;

  public static final String SERIALIZED_NAME_BLINK = "blink";
  @SerializedName(SERIALIZED_NAME_BLINK)
  private DeviceBlink blink;

  public static final String SERIALIZED_NAME_BUS = "bus";
  @SerializedName(SERIALIZED_NAME_BUS)
  private DeviceBus bus;

  public static final String SERIALIZED_NAME_POWER = "power";
  @SerializedName(SERIALIZED_NAME_POWER)
  private DevicePower power;

  public static final String SERIALIZED_NAME_SESSION = "session";
  @SerializedName(SERIALIZED_NAME_SESSION)
  private DeviceSession session;

  public static final String SERIALIZED_NAME_VERSION = "version";
  @SerializedName(SERIALIZED_NAME_VERSION)
  private DeviceVersion version;

  public static final String SERIALIZED_NAME_LOCATION = "location";
  @SerializedName(SERIALIZED_NAME_LOCATION)
  private DeviceLocation location;

  public PeblDevice() {
  }

  public PeblDevice name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public PeblDevice key(String key) {
    
    this.key = key;
    return this;
  }

   /**
   * Get key
   * @return key
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getKey() {
    return key;
  }


  public void setKey(String key) {
    this.key = key;
  }


  public PeblDevice support(DeviceSupport support) {
    
    this.support = support;
    return this;
  }

   /**
   * Get support
   * @return support
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public DeviceSupport getSupport() {
    return support;
  }


  public void setSupport(DeviceSupport support) {
    this.support = support;
  }


  public PeblDevice cloud(DeviceCloud cloud) {
    
    this.cloud = cloud;
    return this;
  }

   /**
   * Get cloud
   * @return cloud
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public DeviceCloud getCloud() {
    return cloud;
  }


  public void setCloud(DeviceCloud cloud) {
    this.cloud = cloud;
  }


  public PeblDevice uptime(DeviceUptime uptime) {
    
    this.uptime = uptime;
    return this;
  }

   /**
   * Get uptime
   * @return uptime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public DeviceUptime getUptime() {
    return uptime;
  }


  public void setUptime(DeviceUptime uptime) {
    this.uptime = uptime;
  }


  public PeblDevice activity(Boolean activity) {
    
    this.activity = activity;
    return this;
  }

   /**
   * Get activity
   * @return activity
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getActivity() {
    return activity;
  }


  public void setActivity(Boolean activity) {
    this.activity = activity;
  }


  public PeblDevice colour(List<Integer> colour) {
    
    this.colour = colour;
    return this;
  }

  public PeblDevice addColourItem(Integer colourItem) {
    if (this.colour == null) {
      this.colour = new ArrayList<>();
    }
    this.colour.add(colourItem);
    return this;
  }

   /**
   * Get colour
   * @return colour
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<Integer> getColour() {
    return colour;
  }


  public void setColour(List<Integer> colour) {
    this.colour = colour;
  }


  public PeblDevice blink(DeviceBlink blink) {
    
    this.blink = blink;
    return this;
  }

   /**
   * Get blink
   * @return blink
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public DeviceBlink getBlink() {
    return blink;
  }


  public void setBlink(DeviceBlink blink) {
    this.blink = blink;
  }


  public PeblDevice bus(DeviceBus bus) {
    
    this.bus = bus;
    return this;
  }

   /**
   * Get bus
   * @return bus
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public DeviceBus getBus() {
    return bus;
  }


  public void setBus(DeviceBus bus) {
    this.bus = bus;
  }


  public PeblDevice power(DevicePower power) {
    
    this.power = power;
    return this;
  }

   /**
   * Get power
   * @return power
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public DevicePower getPower() {
    return power;
  }


  public void setPower(DevicePower power) {
    this.power = power;
  }


  public PeblDevice session(DeviceSession session) {
    
    this.session = session;
    return this;
  }

   /**
   * Get session
   * @return session
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public DeviceSession getSession() {
    return session;
  }


  public void setSession(DeviceSession session) {
    this.session = session;
  }


  public PeblDevice version(DeviceVersion version) {
    
    this.version = version;
    return this;
  }

   /**
   * Get version
   * @return version
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public DeviceVersion getVersion() {
    return version;
  }


  public void setVersion(DeviceVersion version) {
    this.version = version;
  }


  public PeblDevice location(DeviceLocation location) {
    
    this.location = location;
    return this;
  }

   /**
   * Get location
   * @return location
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public DeviceLocation getLocation() {
    return location;
  }


  public void setLocation(DeviceLocation location) {
    this.location = location;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PeblDevice peblDevice = (PeblDevice) o;
    return Objects.equals(this.name, peblDevice.name) &&
        Objects.equals(this.key, peblDevice.key) &&
        Objects.equals(this.support, peblDevice.support) &&
        Objects.equals(this.cloud, peblDevice.cloud) &&
        Objects.equals(this.uptime, peblDevice.uptime) &&
        Objects.equals(this.activity, peblDevice.activity) &&
        Objects.equals(this.colour, peblDevice.colour) &&
        Objects.equals(this.blink, peblDevice.blink) &&
        Objects.equals(this.bus, peblDevice.bus) &&
        Objects.equals(this.power, peblDevice.power) &&
        Objects.equals(this.session, peblDevice.session) &&
        Objects.equals(this.version, peblDevice.version) &&
        Objects.equals(this.location, peblDevice.location);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, key, support, cloud, uptime, activity, colour, blink, bus, power, session, version, location);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PeblDevice {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    support: ").append(toIndentedString(support)).append("\n");
    sb.append("    cloud: ").append(toIndentedString(cloud)).append("\n");
    sb.append("    uptime: ").append(toIndentedString(uptime)).append("\n");
    sb.append("    activity: ").append(toIndentedString(activity)).append("\n");
    sb.append("    colour: ").append(toIndentedString(colour)).append("\n");
    sb.append("    blink: ").append(toIndentedString(blink)).append("\n");
    sb.append("    bus: ").append(toIndentedString(bus)).append("\n");
    sb.append("    power: ").append(toIndentedString(power)).append("\n");
    sb.append("    session: ").append(toIndentedString(session)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("name");
    openapiFields.add("key");
    openapiFields.add("support");
    openapiFields.add("cloud");
    openapiFields.add("uptime");
    openapiFields.add("activity");
    openapiFields.add("colour");
    openapiFields.add("blink");
    openapiFields.add("bus");
    openapiFields.add("power");
    openapiFields.add("session");
    openapiFields.add("version");
    openapiFields.add("location");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to PeblDevice
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!PeblDevice.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PeblDevice is not found in the empty JSON string", PeblDevice.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!PeblDevice.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `PeblDevice` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if ((jsonObj.get("key") != null && !jsonObj.get("key").isJsonNull()) && !jsonObj.get("key").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `key` to be a primitive type in the JSON string but got `%s`", jsonObj.get("key").toString()));
      }
      // validate the optional field `support`
      if (jsonObj.get("support") != null && !jsonObj.get("support").isJsonNull()) {
        DeviceSupport.validateJsonObject(jsonObj.getAsJsonObject("support"));
      }
      // validate the optional field `cloud`
      if (jsonObj.get("cloud") != null && !jsonObj.get("cloud").isJsonNull()) {
        DeviceCloud.validateJsonObject(jsonObj.getAsJsonObject("cloud"));
      }
      // validate the optional field `uptime`
      if (jsonObj.get("uptime") != null && !jsonObj.get("uptime").isJsonNull()) {
        DeviceUptime.validateJsonObject(jsonObj.getAsJsonObject("uptime"));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("colour") != null && !jsonObj.get("colour").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `colour` to be an array in the JSON string but got `%s`", jsonObj.get("colour").toString()));
      }
      // validate the optional field `blink`
      if (jsonObj.get("blink") != null && !jsonObj.get("blink").isJsonNull()) {
        DeviceBlink.validateJsonObject(jsonObj.getAsJsonObject("blink"));
      }
      // validate the optional field `bus`
      if (jsonObj.get("bus") != null && !jsonObj.get("bus").isJsonNull()) {
        DeviceBus.validateJsonObject(jsonObj.getAsJsonObject("bus"));
      }
      // validate the optional field `power`
      if (jsonObj.get("power") != null && !jsonObj.get("power").isJsonNull()) {
        DevicePower.validateJsonObject(jsonObj.getAsJsonObject("power"));
      }
      // validate the optional field `version`
      if (jsonObj.get("version") != null && !jsonObj.get("version").isJsonNull()) {
        DeviceVersion.validateJsonObject(jsonObj.getAsJsonObject("version"));
      }
      // validate the optional field `location`
      if (jsonObj.get("location") != null && !jsonObj.get("location").isJsonNull()) {
        DeviceLocation.validateJsonObject(jsonObj.getAsJsonObject("location"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PeblDevice.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PeblDevice' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PeblDevice> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PeblDevice.class));

       return (TypeAdapter<T>) new TypeAdapter<PeblDevice>() {
           @Override
           public void write(JsonWriter out, PeblDevice value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public PeblDevice read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of PeblDevice given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of PeblDevice
  * @throws IOException if the JSON string is invalid with respect to PeblDevice
  */
  public static PeblDevice fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PeblDevice.class);
  }

 /**
  * Convert an instance of PeblDevice to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

