/*
 * Fingoti API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.fingoti.sdk.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets WifiSlot
 */
@JsonAdapter(WifiSlot.Adapter.class)
public enum WifiSlot {
  
  NUMBER_0(0),
  
  NUMBER_1(1);

  private Integer value;

  WifiSlot(Integer value) {
    this.value = value;
  }

  public Integer getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static WifiSlot fromValue(Integer value) {
    for (WifiSlot b : WifiSlot.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<WifiSlot> {
    @Override
    public void write(final JsonWriter jsonWriter, final WifiSlot enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public WifiSlot read(final JsonReader jsonReader) throws IOException {
      Integer value = jsonReader.nextInt();
      return WifiSlot.fromValue(value);
    }
  }
}

